# Copyright 2023 Practically.io All rights reserved

name: Update Merged Issue Statuses

on: push

# on:
#   push:
#     branches:
#       - main

jobs:
  update-merged-issue-statuses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get issue numbers
        id: get-issue-numbers
        uses: actions/github-script@v5
        with:
          script: |
            const commits = context.payload.commits;
            const issueNumbers = [];
            for (const commit of commits) {
              const matches = commit.message.match(/(Ref: #|Fixes Issue: #)(\d+(\s#\d+)*)/gi);
              if (matches) {
                for (const match of matches) {
                  console.log(match);

                  const issueNumber = match.split('#')[1]; // get the issue number after '#'
                  if (!issueNumbers.includes(issueNumber)) {
                    issueNumbers.push(issueNumber);
                  }
                }
              }
            }
            if (issueNumbers.length === 0) {
              console.log('No issue numbers found in commits');
              return '';
            }

            console.log(issueNumbers);

            return issueNumbers.join(' ');

      - name: Get issue details
        if: steps.get-issue-numbers.outputs.result != ''
        uses: actions/github-script@v5
        with:
          script: |
            const issues = '${{ steps.get-issue-numbers.outputs.result }}'.split(' ');
            for (const issue of issues) {
              console.log(issue);
            }
