# Copyright 2023 Practically.io All rights reserved

name: Update Merged Issue Statuses

on: push

# on:
#   push:
#     branches:
#       - main

jobs:
  update-merged-issue-statuses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get issue numbers
        id: get-issue-numbers
        uses: actions/github-script@v5
        with:
          script: |
            const commits = context.payload.commits;
            const issueNumbers = [];
            for (const commit of commits) {
              const refMatches = commit.message.match(/(Ref: #|Fixes Issue: #)(\d+(\s#\d+)*)/gi);
              if (refMatches) {
                for (const match of refMatches) {
                  const numberMatches = match.match(/#(\d+)/g);
                  for (const numberMatch of numberMatches) {
                    const issueNumber = numberMatch.replace('#', '');
                    if (!issueNumbers.includes(issueNumber)) {
                      issueNumbers.push(issueNumber);
                    }
                  }
                }
              }
            }
            if (issueNumbers.length === 0) {
              console.log('No issue numbers found in commits');
              return '';
            }
            return issueNumbers.join(' ');

      - name: Get issue details
        if: steps.get-issue-numbers.outputs.result != ''
        uses: actions/github-script@v5
        with:
          script: |
            const issues = '${{ steps.get-issue-numbers.outputs.result }}'.split(' ');

            console.log(issues);

            for (const issue of issues) {
              console.log(issue);
            }
